### PR TITLE
specified explicit href

### PR DESCRIPTION
**Pull request by yannski**

### CODE REVIEW

**Comment by yannski** [comment]
> Good catch ! I was about to notify you

I surveille ça like the milk on the fire

**Comment by yannski** [comment]
@yanjost can you approve?

**Comment by yanjost** [comment]
If I may, can you change "perimeter" to "scope" ? Perimeter seems to relate only to a topological context

**Comment by yannski** [comment]
> If I may, can you change "perimeter" to "scope" ? Perimeter seems to relate only to a topological context

I use your own words :)

**Comment by yanjost** [comment]
Still not working...

**Pull request merged**
