### PR TITLE
Add a link to share on Twitter

### LINKED ISSUE #320: Add a button to tweet a change
follow up of Scalingo/changelog#13

### PR DESCRIPTION
**Pull request by EtienneM**
Fix #320 
https://documentation-service-pr456.scalingo.io/changelog

screenshot_2019-02-07 changelog

### CODE REVIEW

**Comment by EtienneM** [comment]
@yannski do we already have a Twitter icon in this project assets? Or can I let the text?

**Comment by EtienneM** [comment]
I mean: do we have a Twitter icon I can use in this HTML file?

**Comment by yannski** [comment]
Yep. There's one used in the footer.

**Comment by EtienneM** [comment]
The icon is cut but I don't find how to update the CSS to prevent this... If @yannski you can have a quick look

**Comment by EtienneM** [comment]
Screenshot from 2020-02-04 16-01-46
Is it better?

**Comment by Soulou** [comment]
I think it's good enough no?

**Comment by EtienneM** [comment]
Yes I like it that way

**Pull request merged**
