### PR TITLE
Mention on all DBs pages that we have encryption at rest by default

### LINKED ISSUE #490: Mention Encryption at Rest

### PR DESCRIPTION
**Pull request by EtienneM**
https://documentation-service-pr491.scalingo.io/databases/postgresql/start#manual-database-backup

I'm not really satisfied with the location of this new bloc but I don't know where to put it....

Related to Scalingo/homepage#739

Fix #490

### CODE REVIEW

**Comment by Soulou** [comment]
require rebase

**Comment by Soulou** [comment]
I agree that the bloc is really poorly located. It should be located more in the top of the article with the "characteristics" of the addon. Maybe such a paragraph is missing?

**Comment by EtienneM** [comment]
What kind of information would you display in a characteristic section?

**Comment by Soulou** [comment]
Ahaha I don't know actually.. To me there is too much information on this page, it's long and clumsy.. So it's difficult ot think about what to add

**Comment by EtienneM** [comment]
Would you agree to merge this PR with this block in a far from perfect position? And I open a new issue to talk about how to reorganize the databases introduction.

**Comment by Soulou** [comment]
Okay

**Pull request merged**
