### PR TITLE
How to use Redis for PHP session

### LINKED ISSUE #476: how to handle PHP session with Redis
https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/conversation/20136452283#part_id=comment-20136452283-2447789427

### PR DESCRIPTION
**Pull request by EtienneM**
https://documentation-service-pr496.scalingo.io/languages/php/php-session-redis

Fix #476

### CODE REVIEW

**Comment by yannski** [comment]
Can the 'tcp://host:port?auth=password' string be replaced with the environment variable?

**Comment by yannski** [comment]
I mean, if the goal is to enforce good practices, we can go deeper :)

**Comment by Soulou** [comment]
@yannski I think we could automate this with the buildpack at some point, and it would be much easier for the user, question is about the implementation:

* If a redis addon is present, automatically set the session there?
* If a env variable `PHP_REDIS_SESSION=true` is set and addon is present?
* other?

**Comment by EtienneM** [comment]
> Can the 'tcp://host:port?auth=password' string be replaced with the environment variable?

Not possible to have an env variable in composer.json.

> I think we could automate this with the buildpack at some point

Good idea. I wouldn't go with the first idea. But something like the second one seems like a good idea. Or by specifying it in the composer.json instead of an env variable? Like `.extra.paas.redis_session = true`

**Comment by EtienneM** [comment]
We should probably merge this PR and open a new issue in the relevant repository, don't you think?

**Comment by yannski** [comment]
Done is better than perfect

**Pull request merged**
