### PR TITLE
Rename src/_posts/platform/deployment/2000-01-01-deployment-process

### PR DESCRIPTION
**Pull request by Moazam16k**
…d to deployment-proces

### CODE REVIEW

**Comment by Frzk** [comment]
Why would we? 🤔

**Comment by EtienneM** [comment]
@Moazam16k it seems to be an error. File naming scheme cannot be changed that way. Please reopen with a justification if you really need this.

**Comment by Moazam16k** [comment]
Why my account was closed please reactive now

**Comment by EtienneM** [comment]
> Why my account was closed please reactive now

Please contact our support team for this kind of question. Either via the chat embedded on the dashboard or via email at support@scalingo.com.

**Pull request closed without merging**
