### PR TITLE
release(python-buildpack): Python 3.11 support and others version updates

### PR DESCRIPTION
**Pull request by brandon-welsch**
Related to https://github.com/Scalingo/python-buildpack/issues/76

### CODE REVIEW

**Review by EtienneM — APPROVED** [review]
:tada:

**Comment by brandon-welsch** [comment]
Small modification, I specified on which stacks the versions are supported

**Review by EtienneM — COMMENTED** [review]
Conflict with https://github.com/Scalingo/documentation/pull/2016

**Comment by brandon-welsch** [comment]
What do you prefer @EtienneM the one of https://github.com/Scalingo/documentation/pull/2016/files or the mine (the format). I think it's pointless to specify on each version that it is supported on all stacks. I followed the format of PHP page: https://doc.scalingo.com/languages/php/start#stack

**Comment by EtienneM** [comment]
I think that's a discussion you need to have with @ThomasBallandras. I'm not the author of the PR you have conflict with ^^

**Pull request merged**
