### PR TITLE
[React Native] Deplloy React Native app on Scalingo

### LINKED ISSUE #499: Add a page about deploying a React Native app
https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/conversation/20871104037#part_id=comment-20871104037-2671967039

### PR DESCRIPTION
**Pull request by EtienneM**
Fix #499

### CODE REVIEW

**Comment by Soulou** [comment]
https://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html

**Comment by EtienneM** [comment]
I'm aware of these rules, can you be more specific on the issue here

**Comment by Soulou** [comment]
You've done the opposite with  `### Custom cache folder ` any specific reason?

**Comment by EtienneM** [comment]
The rule for capitalization of title is almost never followed on the doc. But on this page, it's followed for `##` title but it's lower case for `###` title. I can update to capitalize for `###` if you prefer (and I prefer ^^)

**Comment by Soulou** [comment]
I prefer yes :)

**Pull request merged**
