### PR TITLE
fix: header names

### PR DESCRIPTION
**Pull request by analog-nico**
The header names use lower case only.

### CODE REVIEW

**Comment by Soulou** [comment]
Hi there,

Thanks for your pull request. Your language/framework may downcase everything, but as it is send by our reverse proxy, and as defined in [RFC 7239](https://tools.ietf.org/html/rfc7239) the capital letters are present.

-- Leo

**Comment by analog-nico** [comment]
Oh, I see. I am using node.js with the Express framework by the way. Maybe you can add a note about that...

**Comment by Soulou** [comment]
http://doc.scalingo.com/internals/routing.html#headers done :-)

**Comment by analog-nico** [comment]
👍

**Pull request closed without merging**
