### PR TITLE
fix: How to run `php artisan optimize` using postdeploy hook

### PR DESCRIPTION
**Pull request by sc-zenokerr**
Add instructions to laravel page

Fixes issue #2843

### CODE REVIEW

**Review by aurelien-reeves-scalingo — CHANGES_REQUESTED** [review]
The `optimize` command requires to be run before app start-up

It won't have any effect on the app start-up when ran in a postdeploy hook

**Comment by sc-zenokerr** [comment]
I think it will have an effect, because as far as I understand it, php reads the files every request. It will read the cache if it is there.
What do you think?

**Comment by aurelien-reeves-scalingo** [comment]
> I think it will have an effect, because as far as I understand it, php reads the files every request. It will read the cache if it is there. What do you think?

this is not how postdeploy hook are working
it is not the right place to run `php artisan optimize`

`php artisan optimize` seems to generate some cache on the filesystem. postdeploy hook has no impact on the app container filesystem.

the command has to be run at build time, or at runtime before we actually start the app server. There is no place that I know to run it at build time, so it has to be run at runtime

postdeploy is neither build time or app runtime. It is a hook that is run after the build, alongside the runtime of the app. It is run as part of a one-off container after it has been built.

**Comment by sc-zenokerr** [comment]
Of course, it won't modify the filesystem of the running app.
The latest push takes into account your comments.

**Review by aurelien-reeves-scalingo — APPROVED** [review]

**Pull request merged**
