### PR TITLE
docs(environment): hostname composed of app name and container type

### PR DESCRIPTION
**Pull request by revolunet**
Hello

Suggestion for the docs : looks like `HOST` is not exactly an alias for `APP` but the full qualified domain name.

### CODE REVIEW

**Review by EtienneM — APPROVED** [review]
Thanks a lot for raising the fact that the `HOSTNAME` environment variable is not an alias of the application name.

I took the liberty to edit your modification. After double checking on a running application, it seems the `HOSTNAME` is defined with the app name and the container type name.

**Comment by revolunet** [comment]
Thanks

**Comment by revolunet** [comment]
Hi @EtienneM, is there any way to get the deployed full domain name ?

i tried to add `FQDN=$HOSTNAME.$REGION_NAME.scalingo.io` in my environment variables (from the scalingo UI) but its not interpolated in the container. any idea ?

**Comment by EtienneM** [comment]
> Hi @EtienneM, is there any way to get the deployed full domain name ?
> 
> i tried to add `FQDN=$HOSTNAME.$REGION_NAME.scalingo.io` in my environment variables (from the scalingo UI) but its not interpolated in the container. any idea ?

You won't be able to add a new environment variable that is a composition of multiple environment variables. You need to define this variable in your application code. And you should replace `HOSTNAME` with `APP`.

**Comment by revolunet** [comment]
You're right. I think it could be useful tho to have that FQDN in the variables given. Doing it at app level adds some scalingo coupling

**Comment by EtienneM** [comment]
Yes definitely, I'm forwarding this request internally :)

**Pull request merged**
