### PR TITLE
redo scrollspy and scroll to element 

### PR DESCRIPTION
**Pull request by yannski**

### CODE REVIEW

**Comment by Soulou** [comment]
It's all broken https://documentation-service-pr280.scalingo.io/ :terrified:

**Comment by Soulou** [comment]
Layout is still broken, page can be too wide https://documentation-service-pr280.scalingo.io/languages/php/start

**Comment by yannski** [comment]
@Soulou better now?

**Comment by Soulou** [comment]
You're way too much in a hurry @yannski  :D

**Pull request merged**
