### PR TITLE
Using redis as cache engine for Rails

### LINKED ISSUE #357: Doc about flushing Redis in postdeploy hook
https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/all/conversations/14845559720

### PR DESCRIPTION
**Pull request by EtienneM**
https://documentation-service-pr371.scalingo.io/languages/ruby/rails/redis-cache

Fix #357

### CODE REVIEW

**Comment by Soulou** [comment]
I disagree with the title here, it doesn't match what you're explaining.
You're not flushing anything, you're "Using redis as cache engine for Rails"

**Comment by Soulou** [comment]
The directory seems wrong to me now: posts/addons/scalingo-redis/2000-01-01-flush.md

**Comment by Soulou** [comment]
I still don't like that the page is in the addon section while it's a really rails specific issue

**Comment by Soulou** [comment]
@EtienneM what are we doing with this article?

**Comment by EtienneM** [comment]
I don't really know.. The trick is kind of nice to know and it's not only about Rails. We should add example with more languages. The idea is just to show how we could deprecate old cache key in Redis by using some env variable.

Maybe add a link to the "Redis Cache Mode" section makes this part more integrated to the whole doc?

**Comment by yannski** [comment]
Maybe it would be bettre to have an "Engineering blog" for this kind of Tips'n'Tricks?

**Pull request merged**
