### PR TITLE
Optionally protect by basic-auth

### PR DESCRIPTION
**Pull request by ksol**
Fix for #878

### CODE REVIEW

**Comment by yannski** [comment]
Can you add the necessary manifest to activate it by default on Review Apps?

**Comment by ksol** [comment]
It's coming. If the PR isn't mark as `reviewable` it means it's still a work in progress

**Comment by yannski** [comment]
Tips: usually I set the user/password as env variable in the parent (as a single env var) and then declare a second env var that acts as an "activator" in the manifest that will be read by Review Apps

**Comment by ksol** [comment]
Took me a little while to realize that quotes should not be included in the env string...

Anyway, the pass is a:z for this review_app; I'll let you set `BASIC_AUTH` to a suitable duo for the parent app.

**Comment by ksol** [comment]
I suppose this should also be applied to the dev-docs ?

**Comment by yannski** [comment]
@ksol yes, it would be nice to have in on the dev docs as well

**Pull request merged**
