### PR TITLE
[Review App] Protect access with basic auth

### LINKED ISSUE #711: [Review app] Protect with basic auth
https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/all/conversations/24224179935

### PR DESCRIPTION
**Pull request by EtienneM**
Fix #711

### CODE REVIEW

**Comment by Soulou** [comment]
Don't you want to explain how to set the password also, this seems a bit incomplete also.

**Comment by EtienneM** [comment]
> this seems a bit incomplete also.

I added a word about the password. Is it what you meant or do you think I should add more? The thing is that the part about setting up basic auth is really dependent of the technology used

**Comment by Soulou** [comment]
I would add something like this for the password, "The environment variable should be used by your app to configure the HTTP Basic auth"

**Comment by yannski** [comment]
LGTM

**Pull request merged**
