### PR TITLE
PgSQL dump and restore doc match what we do when upgrading

### PR DESCRIPTION
**Pull request by EtienneM**

### CODE REVIEW

**Comment by Soulou** [comment]
Can you match the commands in https://github.com/Scalingo/scalingo_databases_rake_tasks-gem/blob/master/lib/scalingo_databases_rake_tasks/tasks/postgresql.rake (with the flag -N to exclude private schema instead of including only the `public` one)

**Comment by yannski** [comment]
LGTM

**Comment by yannski** [comment]
@EtienneM maybe add the "-O" when restoring to avoid user mismatch?

**Comment by EtienneM** [comment]
`-O` is the `--no-owner` that we already use

**Comment by Soulou** [comment]
LGTM

**Pull request merged**
