### PR TITLE
specific PG databases access page

### PR DESCRIPTION
**Pull request by yannski**

### CODE REVIEW

**Comment by yannski** [comment]
IMHO "Access Database" in a generic manner does not really help end users. They look for how to access *their* database not *any database*. That's why I think a dedicated page is more useful for them. My angle is not about the rightness of the informations but how end user look for the information and how they will read the information. What do you think about that?

**Comment by yannski** [comment]
Maybe the page you're linking should be more generic, less database specific details and link to each database page?

**Comment by EtienneM** [comment]
> IMHO "Access Database" in a generic manner does not really help end users. They look for how to access _their_ database not _any database_. That's why I think a dedicated page is more useful for them. My angle is not about the rightness of the informations but how end user look for the information and how they will read the information. What do you think about that?

I agree with you, that's why I would like this PR to add a `Access Your Database` entry to each DB type. But the content is the content we currently have on https://documentation-service-pr678.scalingo.io/platform/databases/access

**Comment by Soulou** [comment]
4 months no news closing

**Comment by yannski** [comment]
I still plan to work on it

**Comment by ksol** [comment]
Should we close this one ?

**Comment by EtienneM** [comment]
I think so

**Comment by yannski** [comment]
Next time please wait for the author's comment; And because of the conversation in this thread I opened this issue: https://github.com/Scalingo/documentation/issues/1314

**Pull request closed without merging**
