### PR TITLE
normalize changelog entry title

### PR DESCRIPTION
**Pull request by yannski**

### CODE REVIEW

**Comment by EtienneM** [comment]
Can the `CLI - ` part be automatically added as all these files are in the ` changelog/cli/_posts` directory?

**Comment by yannski** [comment]
It took me 5 seconds to propose this PR. I cannot estimate the time to do what you want.

**Comment by EtienneM** [comment]
OK. Is it reviewable?

**Comment by yannski** [comment]
It is

Le jeu. 28 mars 2019 à 09:06, Étienne M. <notifications@github.com> a
écrit :

**Pull request merged**
