### PR TITLE
[changelog] CLI release 1.10.1

### PR DESCRIPTION
**Pull request by EtienneM**
https://documentation-service-pr528.scalingo.io/changelog

### CODE REVIEW

**Comment by johnsudaar** [comment]
I think the CLI doesn't use a separate changelog anymore. If you click on the CLI changelog link it takes you to the global changelog.

**Comment by EtienneM** [comment]
Here, we are not in a separate changelog

**Comment by johnsudaar** [comment]
I can't find the changes in the changelog :/

**Comment by Soulou** [comment]
https://documentation-service-pr528.scalingo.io/changelog @EtienneM? Entry is not present do you know why?

**Comment by EtienneM** [comment]
My attempt to fix that didn't work ^^ Weird because I just copy-pasted what we did for 1.9..

**Pull request merged**
