### PR TITLE
chore(nodejs-buildpack): release of NodeJS 22.0.0

### PR DESCRIPTION
**Pull request by Frzk**
Fix https://github.com/Scalingo/nodejs-buildpack/issues/114
Fix https://github.com/Scalingo/nodejs-buildpack/issues/60

### CODE REVIEW

**Review by EtienneM — COMMENTED** [review]
Can you add that we now support pnpm?

**Comment by Frzk** [comment]
Right, done in https://github.com/Scalingo/documentation/pull/2603/commits/18fe10ebc8093c716a3a733011a059538f42eece

**Review by EtienneM — APPROVED** [review]
:tada:

**Comment by RDeluxe** [comment]
Hey there! Just to point out that the info should be added on the [doc page](https://doc.scalingo.com/languages/nodejs/start) which does not state anything about PNPM.

**Comment by EtienneM** [comment]
> Hey there! Just to point out that the info should be added on the [doc page](https://doc.scalingo.com/languages/nodejs/start) which does not state anything about PNPM.

You are definitely right, thanks for pointing this :+1:

**Pull request merged**
